[project]
name = "call-protocol"
authors = ["Call Protocol Team"]
description = "A decentralized NFT platform for unique digital asset creation and trading"
telemetry = false
requirements = []
[contracts.call-nft]
path = "contracts/call-nft.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
